name: Backend Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'starter/backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pipenv
      - run: pip install pipenv
      - run: pipenv install --dev
        working-directory: starter/backend
      - run: pipenv run lint
        working-directory: starter/backend

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pipenv
      - run: pip install pipenv
      - run: pipenv install --dev
        working-directory: starter/backend
      - run: pipenv run test
        working-directory: starter/backend

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pipenv
      - run: pip install pipenv
      - run: pipenv install --dev
        working-directory: starter/backend
      - run: pipenv run test
        working-directory: starter/backend
      - run: docker build --tag mp-backend:latest .
        working-directory: starter/backend
